---
# This file is a part of pali_bot
# pali_bot default config

log_level: INFO

# Bot token may be specified here or with PALI_BOT TOKEN environment variable
token: null

about_message: >
    Этот бот создан для некоммерческого использования, материалы взяты с
    сайта <a href='https://theravada.ru'>theravada.ru</a>.


    Наша община существует на пожертвования, вы можете сделать дану на карту
    Сбербанка <code>4276 5500 2002 5576</code>.


    По вопросам и предложениям пишите @Alexandr_Cherkaev, @Max_Kotebus,
    @bergentroll.
